title: wellcome to my blog
description: blog will give you some reflective activities
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: jekyll-architect-theme
plugins:
  - jekyll-feed
